name: Deploy Azure Data Factory

on:
  push:
    branches:
      - ADF

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_RESOURCE_GROUP: cw-mobile-rg
      AZURE_DATA_FACTORY_NAME: sally-tie-out-reporting-poc

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # - name: Set up Azure CLI
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Authenticate with Azure
      run: |
        az login --service-principal -u f07fbbe2-9424-46af-a574-a254e78cec71 -p 6hS8Q~W9TAtIvDl~exiQGSEhgkbpYfbsKRPT5bJq --tenant 0ed45c0a-a9b9-45ca-92b3-6cceb454c222
        # az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    - name: Set Azure subscription
      run: az account set --subscription 0eb16af5-8c5c-42f6-85cb-65f4f74714ce
    #   run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy Data Factory Dataflows
      run: |
        for file in ./dataflow/*.json; do
          dataflow_name=$(basename "$file" .json)
          $dataflow_name
          echo "Deploying dataflow $dataflow_name from $file"
          properties_file="./dataflow/${dataflow_name}.json"
          $properties_file
          az datafactory data-flow create --resource-group cw-mobile-rg --factory-name sally-tie-out-reporting-poc --name "$dataflow_name" --data-flow "@$file" --properties "$properties_file" --flow-type "Flowlet"
        done
          
    # - name: Deploy Data Factory Datasets
    #   run: |
    #     for file in ADF-SALLY/datasets/*.json; do
    #       dataset_name=$(basename "$file" .json)
    #       echo "Deploying dataset $dataset_name from $file"
    #       az datafactory dataset create --resource-group $AZURE_RESOURCE_GROUP --factory-name $AZURE_DATA_FACTORY_NAME --name "$dataset_name" --dataset "@$file"
    #     done

    # - name: Deploy Data Factory Linked Services
    #   run: |
    #     for file in ADF-SALLY/linkedservices/*.json; do
    #       linkedservice_name=$(basename "$file" .json)
    #       echo "Deploying linked service $linkedservice_name from $file"
    #       az datafactory linked-service create --resource-group $AZURE_RESOURCE_GROUP --factory-name $AZURE_DATA_FACTORY_NAME --name "$linkedservice_name" --linked-service "@$file"
    #     done

    # - name: Deploy Data Factory Pipelines
    #   run: |
    #     for file in ADF-SALLY/pipelines/*.json; do
    #       pipeline_name=$(basename "$file" .json)
    #       echo "Deploying pipeline $pipeline_name from $file"
    #       az datafactory pipeline create --resource-group $AZURE_RESOURCE_GROUP --factory-name $AZURE_DATA_FACTORY_NAME --name "$pipeline_name" --pipeline "@$file"
    #     done

    # - name: Deploy Data Factory Triggers
    #   run: |
    #     for file in ADF-SALLY/triggers/*.json; do
    #       trigger_name=$(basename "$file" .json)
    #       echo "Deploying trigger $trigger_name from $file"
    #       az datafactory trigger create --resource-group $AZURE_RESOURCE_GROUP --factory-name $AZURE_DATA_FACTORY_NAME --name "$trigger_name" --trigger "@$file"
    #     done
